[package]
name = "ip-scripting"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ipnet = { version = "2.7.2", features = ["serde"] }
serde = "1.0.160"
